In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv", encoding="latin-1")
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.rename(columns={'v1': 'Category', 'v2': 'Message'}, inplace=True)
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
 df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
def spam(col):
  if col == 'spam':
    return 1
  return 0

In [7]:
df['spam'] = df['Category'].apply(spam)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
#Alternative Method
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [10]:
x_train.shape

(4457,)

In [11]:
x_test.shape

(1115,)

In [12]:
type(x_train)

pandas.core.series.Series

In [13]:
x_train[:4]

3469                          aathi..where are you dear..
5495    Good afternoon, my love ... How goes your day ...
1236                             How much are we getting?
946     Ur cash-balance is currently 500 pounds - to m...
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

3469    0
5495    0
1236    0
946     1
Name: spam, dtype: int64

In [16]:
type(x_train.values)

numpy.ndarray

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(x_train.values)
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 58622 stored elements and shape (4457, 7725)>

In [18]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
x_train_cv.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [20]:
x_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [21]:
v.get_feature_names_out()[1000:1050]

array(['anythiing', 'anythin', 'anything', 'anythingtomorrow', 'anytime',
       'anyway', 'anyways', 'anywhere', 'aom', 'apart', 'apartment',
       'apes', 'apeshit', 'aphexåõs', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appeal',
       'appear', 'applausestore', 'applebees', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'appropriate', 'approx', 'apps',
       'appt', 'appy', 'april', 'aproach', 'aptitude', 'ar', 'arab',
       'arabian', 'arcade', 'archive', 'ard', 'are'], dtype=object)

In [22]:
v.get_feature_names_out().shape

(7725,)

In [23]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_r

In [24]:
v.vocabulary_

{'aathi': 745,
 'where': 7443,
 'are': 1049,
 'you': 7667,
 'dear': 2202,
 'good': 3180,
 'afternoon': 852,
 'my': 4665,
 'love': 4224,
 'how': 3511,
 'goes': 3164,
 'your': 7673,
 'day': 2191,
 'did': 2305,
 'sleep': 6201,
 'hope': 3479,
 'well': 7409,
 'boytoy': 1484,
 'think': 6819,
 'of': 4893,
 'much': 4633,
 'we': 7371,
 'getting': 3125,
 'ur': 7159,
 'cash': 1688,
 'balance': 1216,
 'is': 3741,
 'currently': 2129,
 '500': 537,
 'pounds': 5344,
 'to': 6905,
 'maximize': 4393,
 'in': 3632,
 'now': 4842,
 'send': 5988,
 'go': 3158,
 '86688': 687,
 'only': 4950,
 '150p': 316,
 'msg': 4616,
 'cc': 1709,
 '08718720201': 143,
 'po': 5270,
 'box': 1462,
 '114': 284,
 '14': 304,
 'tcr': 6702,
 'w1': 7289,
 'what': 7434,
 'pa': 5054,
 'tell': 6726,
 'me': 4403,
 'went': 7415,
 'bath': 1251,
 'best': 1331,
 'it': 3753,
 'hard': 3332,
 'be': 1275,
 'with': 7506,
 'person': 5171,
 'when': 7440,
 'know': 3958,
 'that': 6783,
 'one': 4944,
 'more': 4585,
 'step': 6450,
 'foward': 2966,
 'will'

In [26]:
x_train_np = x_train_cv.toarray()
x_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
np.where(x_train_np[0] != 0)

(array([ 745, 1049, 2202, 7443, 7667]),)

In [34]:
x_train[:4]

3469                          aathi..where are you dear..
5495    Good afternoon, my love ... How goes your day ...
1236                             How much are we getting?
946     Ur cash-balance is currently 500 pounds - to m...
Name: Message, dtype: object

In [33]:
x_train[:4][3469]

'aathi..where are you dear..'

In [36]:
x_train_np[0][1049]

np.int64(1)

In [37]:
v.get_feature_names_out()[1049]

'are'

In [39]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [42]:
x_test_cv = v.transform(x_test)

In [43]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       962
           1       0.97      0.92      0.95       153

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [46]:
#0 is ham, 1 is spam
emails = ['Hey mohan, can we get together to watch footbal game tomorrow?',
          'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward',]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [47]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [48]:
clf.fit(x_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [49]:
y_pred = clf.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       962
           1       0.97      0.92      0.95       153

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

